name: CI

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Update to v4
      # 1. Установка зависимостей
      - name: Install dependencies
        uses: npm install
      # 2. Сборка проекта
      - name: Build JS-project
        uses: npm run build  
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3 # Update to v3
        with:
          path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Update to v4

